
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AP Developer Corner
email: austin.douglas.parker@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for talking about ideas and projects.
github_username: aaustinparker
repository: aaustinparker/aaustinparker.github.io
minimal_mistakes_skin: dark  # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: "/assets/images/favicon.ico"
search: true
# search_provider: algolia


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: America/Los_Angeles
locale: en-US

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Austin Parker"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Laidback developer who likes tackling challenges and exploring new tech."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/austindparker"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aaustinparker"

social:
  type: Person
  name: Austin Parker
  links:
    - "https://www.linkedin.com/in/austindparker"
    - "https://github.com/aaustinparker"

atom_feed:
  hide: true

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/austindparker"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aaustinparker"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: true
      share: false
      related: true
      # show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
